### ISSUE TITLE
Slug history

### ISSUE THREAD

**Issue by phillee** [mindblaze/mongoose-url-slugs#11]
When slugs change, it'd be nice to still find it though an old slug. Example:
```
var paul = new Model({ name : 'paul' }).save() // slug: paul
paul.name = 'george'
paul.save() // slug: george
Model.findBySlug('paul') // still returns paul, even though the slug is now george
```

Would probably be implemented with a slugHistory field array that tracks all past slugs
Any interest in a pull request for this?

**Comment by talha-asad** [comment]
Yeah sure, but make sure you take care of collisions etc.
