### ISSUE TITLE
Uniqueness Scope

### ISSUE THREAD

**Issue by itsakap** [mindblaze/mongoose-url-slugs#12]
Is it possible to generate uniqueness within the scope of another field with this plugin? I want to generate slugs that are unique with respect to parent model. Thanks!

**Comment by talha-asad** [comment]
Can you give an example for this.

**Comment by itsakap** [comment]
User has many Articles, generate a slug for each Article that is unique with respect to its parent User (so two Articles may have identical slugs if they belong to two different Users). Does that make sense?

**Comment by talha-asad** [comment]
It does, so i guess its more like a prefix for the slug? So lets say we have Articles in different categories and each Article has a slug prefix for its category. I think that would make sense but how will you keep it dynamic ?

**Comment by talha-asad** [comment]
BTW i think what you are trying to do, you can already achieve by setting ```index_unique``` to false. And the plugin would allow more than one article to have the same slug. You can then query the Mongo with the additional user parameter.

**Comment by talha-asad** [comment]
If your problem is solved, please close this.
