### ISSUE TITLE
Create Slug for Sub documents?

### ISSUE THREAD

**Issue by viztastic** [mindblaze/mongoose-url-slugs#13]
Hi Talha,

Thanks for this module, it's great. I have a particular use case in mind:

I have a document (e.g. "Book") I currently use mongoose-url-slugs to create a slug for it. But now I have sub documents (e.g. Chapters within the book) that I'd also like to create a slug for each individual chapter. 

Example Schema

```json
{ 
  "bookName" : "Bears go Shopping",
  "slug" : "bears-go-shopping",
  "chapters": 
               [{
                "chapterName":"Authors Intro",
                "slug":"authors-intro"
                     },{
                "chapterName":"A beautiful day",
                "slug":"a-beautiful-day"
               }]
}
```

Is there a way to achieve this?

**Comment by viztastic** [comment]
I should note that I have tried doing that to date, I have a "BookSchema" and a "chapterSchema" htat look something like this

```javascript

var urlSlug = require('mongoose-url-slugs');

var bookSchema = new Schema({
     "bookName" : {type:String},
     "chapters": [chapterSchema]
})

var chapterSchema = new Schema({
    "chapterName" : {type:String}

})

bookSchema.plugin(urlSlug("bookName"));
chapterSchema.plugin(urlSlug("chapterName"));

```

The example is extremely simplified, but hopefully it conveys what I am trying to do.

**Comment by talha-asad** [comment]
Please empty the collections first and then try again. The error message generally pops up if you already have documents that don't obey the index definitions.

**Comment by viztastic** [comment]
Hi @talha-asad , thanks for the response, I did the following steps:

```
$ mongo [DatabaseName]
$ db.collection.drop()
```

Then I re-ran the node app and I got this error instead: 

![image](https://cloud.githubusercontent.com/assets/8556736/12087929/12fbdac4-b32b-11e5-9778-2ddcc996561b.png)

**Comment by talha-asad** [comment]
What version of mongoose, mongodb and node are you using. I'll try and reproduce this error.

**Comment by viztastic** [comment]
HI @talha-asad 

Sorry for the belated response:

Mongoose Version: 4.3.4
NodeJS version: 4.2.1
MongoDB version: 3.0.5

Much appreciated!

**Comment by talha-asad** [comment]
Sorry took me a while to get back to this, i just noticed that you are specifying that field in the schema definition as well when it is automatically added (Which is the default setting). Try remove it from the schema block and than give it another try.
