### ISSUE TITLE
Missing index.js in `node_modules/mongoose-url-slugs`

### ISSUE THREAD

**Issue by neagle** [mindblaze/mongoose-url-slugs#15]
After installing this package with `npm install -S mongoose-url-slugs`, I've been getting "module not found" errors when I try to actually run my app.

I checked the contents of `node_modules/mongoose-url-slugs`, and all I see is this:

```
history.md
LICENSE
Readme.md
node_modules
package.json
```

It's notably missing an `index.js` file, which the git repo definitely appears to have. I've tried deleting and reinstalling, with the same issue.

Is there anything I might be doing wrong on my end? I've never run into this issue with a package before. Is it possible there's something wrong with the package that got published to npm?

Thanks for any help you're able to give: I appreciate it!

**Comment by talha-asad** [comment]
Thanks for pointing it out, i don't know how it got removed from the npm registry. I am going to publish a new version and see if i can put it back in. I can't understand how it happened so far.

**Comment by talha-asad** [comment]
I just published a new version `0.2.0` and it seems to have the index.js file. I don't know how it got removed, probably npm had a bug while publishing the package. Please try using that and close this if it works for you. Thanks again.

**Comment by neagle** [comment]
I just reinstalled, and everything's as it should be. Thanks a bunch for your quick response and for your help!

**Comment by talha-asad** [comment]
@neagle #16 pointed pretty much the same issue with the new NPM version so i unpublished all versions from 0.1.8 onwards till 0.2.0

Just a heads up for you, to maybe change your version number to the latest (0.2.1).
There is no code difference so hopefully it'll be painless. Thanks.
