### ISSUE TITLE
Empty directory on npm install

### ISSUE THREAD

**Issue by mtimofiiv** [mindblaze/mongoose-url-slugs#16]
When installing this module with NPM (at least NPM 3), the folder does not actually contain any javascript files (and therefore cause errors when requiring it into the application).

This happens on version 0.1.8 and higher (including the current version).

**Comment by talha-asad** [comment]
Yes this is something in the npm (atleast that is what i think so far) that caused an issue in some of the versions i published. I don't really know why it happens, have look at #15 

I'll look into this again. If you can help me debug this it would be great.

**Comment by mtimofiiv** [comment]
No problem! Sorry for the duplicate then.

You could try to explicitly define the files you're including like so:
https://github.com/mtimofiiv/mongoose-iban/blob/master/package.json

Here's the docs for that:
https://docs.npmjs.com/files/package.json#files

**Comment by talha-asad** [comment]
Thanks a bunch for that pointer, i am guessing this is a recent change and i must've missed it. I'll publish a new version and delete older ones.

**Comment by talha-asad** [comment]
I unpublished 0.1.8 till 0.2.0 and published a new package with the version 0.2.1
Please see if it works out for you, if it does please close this issue. Thanks alot!

**Comment by mtimofiiv** [comment]
Looks fixed for me, thanks!
