### ISSUE TITLE
function that generate the slug

### ISSUE THREAD

**Issue by RamyRais** [mindblaze/mongoose-url-slugs#18]
Hello,
I have already some document in the database and i am migrating ti use slug how can i update all my document so they have slug field?

I was looking for a function generate the slug something like URLSlugs.generate(text, options) and looping through all the document and generate it.

**Comment by simison** [comment]
Would just saving each document work?

```javascript
Tank.findById(id, function (err, tank) {
  if (err) return handleError(err);
  
  tank.save(function (err) {
    if (err) return handleError(err);
    // Done, you should now have a slug
  });
});
```

**Comment by RamyRais** [comment]
I was using update and it seems with update it does not work but with save it work.
Thank you.
