### ISSUE TITLE
Ability to specify which model hook the plugin runs on

### ISSUE THREAD

**Issue by mtimofiiv** [mindblaze/mongoose-url-slugs#28]
Currently, the slug building is run on [pre-validate](https://github.com/mindblaze/mongoose-url-slugs/blob/master/index.js#L178). What about if this is the default, but one could overwrite this via config option if needed?

The usecases for this are esoteric, it's true. I'd be more than happy to provide a PR.

**Comment by talha-asad** [comment]
I'd accept it.

**Comment by mtimofiiv** [comment]
Ok cool, I submitted a PR here: https://github.com/mindblaze/mongoose-url-slugs/pull/29
