### ISSUE TITLE
doc.get is not a function with onHook: 'update'

### ISSUE THREAD

**Issue by ellipticaldoor** [mindblaze/mongoose-url-slugs#30]
When I set the onHook to update I get the following error:

```
doc.get is not a function
```

**Comment by talha-asad** [comment]
Please provide with a reproduction.

**Comment by ellipticaldoor** [comment]
I'm using this framework that generates api rest.

When using the post method mongoose called the code inside the schema.pre.('save', function(){})
but with method post save is not called, instead it calls update so the slug was not being generated.

So I solved this issue making this plugin https://github.com/ellipticaldoor/slugify-mongoose
